version: '2'
services:
  app:
    build: .
    volumes_from:
      - bundle
    volumes:
      - .:/app
      - ../:/src
  bundle:
    image: busybox
    volumes:
      - /bundle
volumes:
  bundle:
  src:
